apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-guestbook
  labels:
    app: guestbook
    tier: frontend
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
    release: {{ .Release.Name }}

